### ISSUE TITLE
После обновы бота просит обновить pip, но он так последней версии 

### ISSUE THREAD

**Issue by Sudn1** [Laysinity/Hamster-Kombat-auto-farming-bot#4]
![image](https://github.com/Laysinity/Hamster-Kombat-auto-farming-bot/assets/172081791/44571102-846a-43fb-9b24-29f049cea393)

**Comment by Sudn1** [comment]
![image](https://github.com/Laysinity/Hamster-Kombat-auto-farming-bot/assets/172081791/d643ec6b-de6e-4bfa-bbd4-f0de598fef62)
Скачал 3.11.9, проблема с pip ушла, но теперь при запуске вот так

**Comment by Sudn1** [comment]
DEPRECATION: pyaes is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559 
 Еще такую ошибку выдает

**Comment by Sudn1** [comment]
Попробовал установить бота до обновления, все работает

**Comment by Sudn1** [comment]
С обновленным ботом для tapswap такая же ошибка 
![image](https://github.com/Laysinity/Hamster-Kombat-auto-farming-bot/assets/172081791/0addf0bc-6dd8-4eb4-a1f6-a83c6b9ac150)

**Comment by Laysinity** [comment]
В ошибке написано, что неправильно введены API_ID и API_HASH.

**Comment by Sudn1** [comment]
Вводил как в примере

**Comment by Sudn1** [comment]
их же без пробела и тому подобного надо вводить?

**Comment by Sudn1** [comment]
Точно так же на старой версии ввожу и нормально все

**Comment by Sudn1** [comment]
> В ошибке написано, что неправильно введены API_ID и API_HASH.

Или их как то по новому надо вводить?
