### ISSUE TITLE
Ошибка в параметре SLEEP_BY_MIN_ENERGY	

### ISSUE THREAD

**Issue by kirajok** [Laysinity/Hamster-Kombat-auto-farming-bot#5]
pydantic_core._pydantic_core.ValidationError: 1 validation error for Settings
SLEEP_BY_MIN_ENERGY
  Input should be a valid list [type=list_type, input_value=20, input_type=int]
    For further information visit https://errors.pydantic.dev/2.6/v/list_type

**Comment by Laysinity** [comment]
Пиши это не как число, а как диапазон например [10,50]

**Comment by kirajok** [comment]
Заработало, спасибо, смутило пример и на скриншоте и в примере на главной странице проекта.

**Comment by Laysinity** [comment]
Спасибо, изменю Readme
